
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: postgres

jpa:
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob:
          non_contextual_creation: true

  hibernate:
    ddl-auto: update
  
  # App Properties
security:
  app:
    jwtSecret: secretKey
    jwtExpirationMs: 86400000
server:
  port: 8081